Restore `OrderList`'s columns classnames
commercelayer/commercelayer-react-components pull request #440
Opened 2023-10-24 14:28 UTC by pfferrari

## What I did

I restored the usage of columns defined `className` and `titleClassNames` props that probably got lost during order subscriptions refactoring of `OrderList` component.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests).
- [ ] Make sure to add/update documentation regarding your changes.
- [x] You are **NOT** deprecating/removing a feature.

2023-10-24 14:43 UTC, malessani submitted a review, later dismissed
👍

2023-10-24 14:48 UTC, gciotola requested changes

2023-10-24 14:48 UTC, gciotola commented on packages/react-components/src/components/orders/OrderList.tsx
> +              className: `${columns[k]?.titleClassName} ${
```suggestion
              className: `${columns[k]?.titleClassName ?? ''} ${
```
prevent `undefined` from being printed as a string

2023-10-24 14:57 UTC, pfferrari commented on packages/react-components/src/components/orders/OrderList.tsx
> +              className: `${columns[k]?.titleClassName} ${
Uh.. Sorry for the oversight.. I fixed it!

2023-10-24 15:04 UTC, gciotola approved these changes

2023-10-25 09:54 UTC, malessani approved these changes
👍

2023-10-25 10:03 UTC, merged