Add documentation for exported hooks
commercelayer/commercelayer-react-components pull request #463
Opened 2024-01-02 17:19 UTC by gciotola

## What I did

I've added documentation (in storybook) for the following hooks:
- useCommerceLayer
- useOrderContainer
- useCustomerContainer 

## How to test

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests).
- [x] Make sure to add/update documentation regarding your changes.
- [x] You are **NOT** deprecating/removing a feature.

2024-01-02 17:36 UTC, malessani requested changes

2024-01-02 17:36 UTC, malessani commented on packages/docs/stories/hooks/001.useCommerceLayer.mdx
> +This hook returns an object that can be destructured to access an instnce of the `sdkClient` function.
```suggestion
This hook returns an object that can be destructured to access an instance of the `sdkClient` function.
```

2024-01-02 17:36 UTC, malessani commented on packages/docs/stories/hooks/001.useCommerceLayer.mdx
> +Please not that the `sdkClient()` function might not always exist, this because it needs to access the React context that could also be `undefined`.
```suggestion
Please note that the `sdkClient()` function might not always exist, this because it needs to access the React context that could also be `undefined`.
```

2024-01-02 17:36 UTC, malessani commented on packages/docs/stories/hooks/002.useOrderContainer.mdx
> +## The addToCart method
is it possible also to trigger the external price?

2024-01-02 17:36 UTC, malessani commented on packages/docs/stories/hooks/002.useOrderContainer.mdx
> +This is usefull since we discourage the creation of empty orders, but they should be created only when the user adds a line item to the cart.
```suggestion
This is useful since we discourage the creation of empty orders, but they should be created only when the user adds a line item to the cart.
```

2024-01-02 17:36 UTC, malessani commented on packages/docs/stories/hooks/002.useOrderContainer.mdx
> +and the addition of the `line_items`, instead of using the methods provided by the `useOrderContainer` hook.
```suggestion
and the addition of the `line_items`, instead of using methods provided by the `useOrderContainer` hook.
```

2024-01-02 17:36 UTC, malessani commented on packages/react-components/src/hooks/useCommerceLayer.ts
> +  /** This method can be used to initialize an sdk client and perform list, retrieve, update or delete operation on any resource */
```suggestion
  /** This method can be used to initialize an sdk client and perform list, retrieve, update or delete operations on any resource */
```

2024-01-02 17:36 UTC, malessani commented on packages/react-components/src/hooks/useOrderContainer.ts
> +  /** Allows to add a SKU or a Bundle to the order stored in the context */
```suggestion
  /** Allow to add a SKU or a Bundle to the order stored in the context */
```

2024-01-02 17:36 UTC, malessani commented on packages/react-components/src/hooks/useOrderContainer.ts
> +  /** Allows to create a new order and store it in the OrderContainer context */
```suggestion
  /** Allow to create a new order and store it in the OrderContainer context */
```

2024-01-04 09:43 UTC, gciotola commented on packages/docs/stories/hooks/002.useOrderContainer.mdx
> +## The addToCart method
Yes, it's possible with ` addToCart({ lineItem: { externalPrice: true }}) `.
I've updated the doc!

2024-01-04 09:53 UTC, acasazza approved these changes
Nice shot!

2024-01-04 09:59 UTC, merged